const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const toast = (msg) => { const t=$('#toast') || document.createElement('div'); t.id='toast'; t.className='toast show'; t.textContent=msg; document.body.appendChild(t); setTimeout(()=>t.classList.remove('show'),3000); };
function activeNav(){ const page=location.pathname.split('/').pop()||'index.html'; $$('.nav a,.mobile-nav a').forEach(a=>{ if(a.getAttribute('href')===page) a.classList.add('active'); }); }
function requireLogin(){ if(!localStorage.getItem('sittaUser') && !['index.html','login.html',''].includes(location.pathname.split('/').pop())) location.href='index.html'; }
function currentUser(){ try{return JSON.parse(localStorage.getItem('sittaUser')||'null')}catch{return null} }
function fillUser(){ const u=currentUser(); $$('.userName').forEach(e=>e.textContent=u?u.nama:'Tamu'); $$('.userRole').forEach(e=>e.textContent=u?`${u.role} • ${u.lokasi}`:'SITTA UT'); const av=$('.avatar'); if(av && u) av.textContent=u.nama.split(' ').map(x=>x[0]).slice(0,2).join(''); }
function greet(){ const h=new Date().getHours(); let g=h<11?'Selamat pagi':h<15?'Selamat siang':h<18?'Selamat sore':'Selamat malam'; const el=$('#greeting'); if(el) el.textContent=g; }
function setupLogout(){ const b=$('#logoutBtn'); if(b) b.onclick=()=>{localStorage.removeItem('sittaUser'); location.href='index.html'} }
function modal(id, show=true){ const m=$(id); if(m) m.classList.toggle('show',show); }
function initLogin(){ const form=$('#loginForm'); if(!form) return; form.addEventListener('submit', e=>{ e.preventDefault(); const email=$('#email').value.trim(); const pass=$('#password').value.trim(); const user=(window.dataPengguna||[]).find(u=>u.email===email && u.password===pass); if(!user){ toast('Email/password yang anda masukkan salah'); return; } localStorage.setItem('sittaUser', JSON.stringify(user)); location.href='dashboard.html'; }); $$('.open-modal').forEach(btn=>btn.onclick=()=>modal(btn.dataset.target,true)); $$('.close-modal').forEach(btn=>btn.onclick=()=>modal(btn.dataset.target,false)); }
function initDashboard(){ const el=$('#stockSummary'); if(el && window.dataBahanAjar){ const total=dataBahanAjar.reduce((a,b)=>a+Number(b.stok),0); el.textContent=total.toLocaleString('id-ID'); } const doCount=$('#doCount'); if(doCount && window.dataTracking) doCount.textContent=Object.keys(dataTracking).length; }
function renderStok(){ const body=$('#stokBody'); if(!body || !window.dataBahanAjar) return; body.innerHTML=''; dataBahanAjar.forEach((b,i)=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td><img class="cover" src="${b.cover}" alt="${b.namaBarang}" onerror="this.style.display='none'"></td><td><b>${b.namaBarang}</b><br><span class="muted">${b.kodeBarang}</span></td><td>${b.kodeLokasi}</td><td>${b.jenisBarang}</td><td>${b.edisi}</td><td class="${b.stok<200?'stock-low':'stock-ok'}">${b.stok}</td><td><button class="btn btn-ghost" onclick="hapusStok(${i})">Hapus</button></td>`; body.appendChild(tr); }); const total=$('#totalItem'); if(total) total.textContent=dataBahanAjar.length; }
window.hapusStok=(i)=>{ dataBahanAjar.splice(i,1); renderStok(); toast('Baris stok berhasil dihapus'); };
function initStok(){ renderStok(); const f=$('#stokForm'); if(!f) return; f.addEventListener('submit', e=>{ e.preventDefault(); const b={ kodeLokasi:$('#kodeLokasi').value.trim(), kodeBarang:$('#kodeBarang').value.trim(), namaBarang:$('#namaBarang').value.trim(), jenisBarang:$('#jenisBarang').value.trim(), edisi:$('#edisi').value.trim(), stok:Number($('#stok').value), cover:'img/pengantar_komunikasi.jpg' }; if(!b.kodeLokasi||!b.kodeBarang||!b.namaBarang||!b.stok){ toast('Lengkapi data stok terlebih dahulu'); return; } dataBahanAjar.push(b); f.reset(); renderStok(); toast('Data bahan ajar baru berhasil ditambahkan'); }); }
function initTracking(){ const form=$('#trackingForm'); if(!form) return; form.addEventListener('submit', e=>{ e.preventDefault(); const no=$('#nomorDO').value.trim(); const d=(window.dataTracking||{})[no]; const box=$('#trackingResult'); if(!d){ box.style.display='block'; box.innerHTML='<div class="card empty">Nomor Delivery Order tidak ditemukan. Coba <b>2023001234</b> atau <b>2023005678</b>.</div>'; return; } const progress=d.status.toLowerCase().includes('selesai')?100:d.status.toLowerCase().includes('dikirim')?85:55; box.style.display='block'; box.innerHTML=`<div class="grid grid-2"><div class="card"><span class="eyebrow">Nomor DO</span><h2>${no}</h2><p class="muted">Nama Mahasiswa: <b>${d.nama}</b></p><div class="progress"><span style="width:${progress}%"></span></div><p><span class="badge badge-blue">${d.status}</span></p></div><div class="card"><h3>Detail Pengiriman</h3><p>Ekspedisi: <b>${d.ekspedisi}</b></p><p>Tanggal kirim: <b>${d.tanggalKirim}</b></p><p>Jenis paket: <b>${d.paket}</b></p><p>Total pembayaran: <b>${d.total}</b></p></div></div><div class="card"><h3>Riwayat Perjalanan</h3><div class="timeline">${d.perjalanan.map(p=>`<div class="timeline-item"><b>${p.waktu}</b><br><span class="muted">${p.keterangan}</span></div>`).join('')}</div></div>`; }); }
function initLaporan(){ const wrap=$('#rekapStok'); if(wrap && window.dataBahanAjar){ const total=dataBahanAjar.reduce((a,b)=>a+b.stok,0); const low=dataBahanAjar.filter(b=>b.stok<200).length; wrap.innerHTML=`<div class="card"><b>Total Judul</b><strong>${dataBahanAjar.length}</strong><p class="muted">Jumlah semua stok: ${total.toLocaleString('id-ID')}</p></div><div class="card"><b>Perlu Monitoring</b><strong>${low}</strong><p class="muted">Item dengan stok di bawah 200.</p></div>`; } }
function initHistori(){ const body=$('#historiBody'); if(!body || !window.dataTracking) return; body.innerHTML=Object.entries(dataTracking).map(([no,d])=>`<tr><td><span class="code">${no}</span></td><td>${d.nama}</td><td>${d.ekspedisi}</td><td>${d.tanggalKirim}</td><td><span class="badge badge-green">${d.status}</span></td><td>${d.total}</td></tr>`).join(''); }
document.addEventListener('DOMContentLoaded',()=>{ requireLogin(); activeNav(); fillUser(); greet(); setupLogout(); initLogin(); initDashboard(); initStok(); initTracking(); initLaporan(); initHistori(); });
